### ISSUE TITLE
Can't get a token

### ISSUE THREAD

**Issue by comm9200** [dparnell/samsung-cac#1]
The method described here to get the Token doesn't seem to work for me. It's mentioned that it was retrieved another way? Any tips for us?

**Comment by dparnell** [comment]
From memory I used a hacked version of the official Samsung app. I decompiled the app and then got enough of it working to go through the registration process and dump out the token.

One thing you will need to be aware of is that modern versions of node may have trouble connecting to the device as it uses a very old version of TLS that is disabled on most newer systems.

**Comment by comm9200** [comment]
Thanks @dparnell, I managed to get the token by using a different homebridge plugin: https://www.npmjs.com/package/homebridge-plugin-samsung-air-conditioner

It comes with a terminal command that returns the token.

**Comment by dparnell** [comment]
Cool :) Happy hacking :)
